server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://roundhouse.proxy.rlwy.net:23386/railway"
    username: root
    password: lCGqOVqPYipELIrqOIuNYqCybZeyxVej
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true