server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://root:gOfwBaPDVpXfdyNNtHTuKOrOSUOrFlAP@mysql.railway.internal:3306/railway"
    username: root
    password: gOfwBaPDVpXfdyNNtHTuKOrOSUOrFlAP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
